name = "BcnFoodies"
description = "A list of Google Maps of restaurants curated by https://bcneng.org/ community."
keywords = "food, foodies, barcelona, maps, eating"
image = "bcnfoodies.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "https://bcneng.github.io/foodies/"

[[sections]]
title = "BcnFoodies"
description = "A list of Google Maps of restaurants curated by bcneng.org community."
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Barcelona"
description = ""
url = "https://maps.app.goo.gl/hQe9Tmh8FVyRN4Vc8"
[[sections.items]]
title = "Madrid"
description = ""
url = "https://maps.app.goo.gl/vy7wnkuxb23igrHu5"
[[sections.items]]
title = "Zaragoza"
description = ""
url = "https://maps.app.goo.gl/kEm6NEZopSuF7u1M7"
[[sections.items]]
title = "Rome"
description = ""
url = "https://maps.app.goo.gl/a4Mwqk7pj6zdc36U6"
[[sections.items]]
title = "Paris"
description = ""
url = "https://maps.app.goo.gl/DYpVH2PzdETCMCqh6"
[[sections.items]]
title = "Tortillas - Barcelona"
description = ""
url = "https://maps.app.goo.gl/74bkzNS2MYy3h5hX9"

[[sections]]
title = "Links"
description = "Bcn Engineering"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Website"
url = "https://bcneng.org/"
[[sections.items]]
title = "Github"
url = "https://github.com/bcneng"
[[sections.items]]
title = "Linkedin"
url = "https://www.linkedin.com/company/bcneng/"
[[sections.items]]
title = "Twitter"
url = "https://x.com/bcn_eng"
